pipeline:
  name: ci
  identifier: ci
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1742571287290
        repoName: everops-mat/go-web-test
        build: <+input>
  stages:
    - stage:
        name: build-docker-image
        identifier: builddockerimage
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: |-
                      echo "Hello, World!"
                      ls
                      env
                      go version
              - step:
                  type: BuildAndPushDockerRegistry
                  name: BuildAndPushDockerRegistry_1
                  identifier: BuildAndPushDockerRegistry_1
                  spec:
                    connectorRef: account.harnessImage
                    repo: test
                    tags:
                      - test
                    caching: true
                    envVariables:
                      PLUGIN_DRY_RUN: "true"
