---
repos:
  - repo: local
    hooks:
      - id: enforce-branch-naming
        name: Enforce Branch Naming
        entry: bash ./scripts/enforce-branch-naming.sh
        language: system
        pass_filenames: false
        always_run: true
      - id: block-sensative-files
        name: Block Sensitive Files
        entry: bash ./scripts/block-sensative-files.sh
        language: system
        pass_filenames: false
        always_run: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: validate-toml
      - id: go-mod-tidy
      - id: go-imports
      - id: go-fmt
#      - id: go-vet
#        name: Run go vet
#        language: system
#        entry: go vet ./...
#        pass_filenames: false
#        always_run: true
      - id: golangci-lint
      - id: no-go-testing
      - id: go-unit-tests
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL3007"]
