---
repos:
  - repo: local
    hooks:
      - id: enforce-branch-naming
        name: Enforce Branch Naming
        entry: bash ./scripts/enforce-branch-naming.sh
        language: system
        args: ["feature/*", "hotfix/*", "bugfix/*", "ci/*", "release/*"]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: detect-private-key
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: validate-toml
      - id: go-fmt
      - id: go-imports
      - id: no-go-testing
      - id: golangci-lint
      - id: go-unit-tests
  - repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.1b3
    hooks:
      - id: hadolint
        args: ["--ignore", "DL3008", "--ignore", "DL3007", "--ignore", "DL4006"]
#   - repo: local
#     hooks:
#       - id: cgi-test
#         name: Run perl tests on cgi script
#         entry: ./eo_test.pl
#         language: script
#         types: [file]
#         files: ^eo\.pl$
