---
name: Enforce Branch Naming

on:
  push:
    branches: ignore
      - main
      - develop
  pull_request:

jobs:
  enforce-branch-naming:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get branch name
        run: |
          echo "Checking branch name..."
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            BRANCH_NAME="${{ github.event.pull_request.head.ref }}"
          else
            BRANCH_NAME="${{ github.ref_name }}"
            BRANCH_NAME="${BRANCH_NAME#refs/heads/}"
          fi

          echo "Branch name: $BRANCH_NAME"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Enforce branch naming
        run: |
          ALLOWED_BRANCH_PREFIXES="feature/* hotfix/* bugfix/* ci/* release/*"
          REGEX=$(echo "$ALLOWED_BRANCH_PREFIXES" | sed -e 's/ /|/g' | sed -e 's/\*/[a-z0-9._-]*/g')

          if [[ ! $BRANCH_NAME =~ ^($REGEX)$ ]]; then
            echo "Branch name '$BRANCH_NAME' is invalid."
            echo "Allowed branch prefixes: $ALLOWED_BRANCH_PREFIXES"
            exit 1
          fi
          echo "Branch name $BRANCH_NAME is valid."
